// swift/DetDocCore/Sources/DetDocCore/Agent/AgentRunnerFactory.swift
import Foundation

/// Selects the `AgentRunner` implementation from config. Default (`pi-rpc`) drives the real
/// `pi` binary; `fake` keeps the deterministic offline runner for development without pi.
public enum AgentRunnerFactory {
    public static func make(config: DetDocConfig) -> any AgentRunner {
        switch config.agent.provider {
        case "fake":
            return FakeAgentRunner(target: "src/app.swift", content: "// generated by DetDoc\n")
        default:
            return PiAgentRunner()
        }
    }
}
